version: '3.8'

services:
  protomock:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"   # HTTP
      - "9090:9090"   # gRPC
    volumes:
      - ./mocks:/app/mocks:ro
