version: '3.8'

services:
  protomock:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"   # HTTP
      - "8086:8086"   # gRPC
    volumes:
      - ./mocks:/app/mocks:ro
